"""add phone_number

Revision ID: 4453657d26d4
Revises: a01dd75f524d
Create Date: 2025-12-20 18:26:54.307395
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4453657d26d4'
down_revision: Union[str, None] = 'a01dd75f524d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('contact', sa.VARCHAR(length=32), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=32), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'phone_number')
    op.drop_column('payments', 'contact')
    # ### end Alembic commands ###