"""add payment table

Revision ID: 5e3a43662f85
Revises: a28928b89a88
Create Date: 2025-11-20 19:30:55.337742
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3a43662f85'
down_revision: Union[str, None] = 'a28928b89a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created','paid','failed')", name='ck_payments_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.drop_index('idx_ai_insights_user_id', table_name='ai_insights')
    op.drop_index('idx_test_results_created_at', table_name='test_results')
    op.drop_index('idx_test_results_test_id', table_name='test_results')
    op.drop_index('idx_test_results_user_id_completed', table_name='test_results')
    op.drop_index('idx_test_results_user_test_created', table_name='test_results')
    op.add_column('users', sa.Column('payment_completed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_completed')
    op.create_index('idx_test_results_user_test_created', 'test_results', ['user_id', 'test_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_test_results_user_id_completed', 'test_results', ['user_id', 'is_completed'], unique=False)
    op.create_index('idx_test_results_test_id', 'test_results', ['test_id'], unique=False)
    op.create_index('idx_test_results_created_at', 'test_results', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_ai_insights_user_id', 'ai_insights', ['user_id'], unique=False)
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###