"""add counseling col

Revision ID: 6b3823ffd311
Revises: 8fac717e4f59
Create Date: 2026-04-02 10:32:08.636725
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3823ffd311'
down_revision: Union[str, None] = '8fac717e4f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    # Add column with server_default for existing rows, then alter to not null
    op.add_column('users', sa.Column('counseling_completed', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('counseling_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_counseling_completed'), 'users', ['counseling_completed'], unique=False)
    # Alter column to not null after setting default
    op.alter_column('users', 'counseling_completed', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_counseling_completed'), table_name='users')
    op.drop_column('users', 'counseling_completed_at')
    op.drop_column('users', 'counseling_completed')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    # ### end Alembic commands ###