"""change payment model

Revision ID: 8fac717e4f59
Revises: 4453657d26d4
Create Date: 2025-12-27 22:34:46.772945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fac717e4f59'
down_revision: Union[str, None] = '4453657d26d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('plan_type', sa.VARCHAR(length=32), nullable=True))
    op.create_index(op.f('ix_payments_plan_type'), 'payments', ['plan_type'], unique=False)
    op.add_column('users', sa.Column('plan_type', sa.VARCHAR(length=32), nullable=True))
    op.create_index(op.f('ix_users_plan_type'), 'users', ['plan_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_plan_type'), table_name='users')
    op.drop_column('users', 'plan_type')
    op.drop_index(op.f('ix_payments_plan_type'), table_name='payments')
    op.drop_column('payments', 'plan_type')
    # ### end Alembic commands ###
