"""add index

Revision ID: 95f6610c12ad
Revises: c13c0fac2aae
Create Date: 2025-11-09 20:34:31.614945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f6610c12ad'
down_revision: Union[str, None] = 'c13c0fac2aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ai_insights_generated_at', 'ai_insights', ['generated_at'], unique=False)
    op.create_index('idx_ai_insights_type_status', 'ai_insights', ['insights_type', 'status'], unique=False)
    op.create_index('idx_ai_insights_user_status', 'ai_insights', ['user_id', 'status'], unique=False)
    op.create_index('idx_ai_insights_user_type', 'ai_insights', ['user_id', 'insights_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_confidence_score'), 'ai_insights', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_ai_insights_created_at'), 'ai_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_generated_at'), 'ai_insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_generation_duration'), 'ai_insights', ['generation_duration'], unique=False)
    op.create_index(op.f('ix_ai_insights_insights_type'), 'ai_insights', ['insights_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_model_used'), 'ai_insights', ['model_used'], unique=False)
    op.create_index(op.f('ix_ai_insights_status'), 'ai_insights', ['status'], unique=False)
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    op.create_index('idx_options_question_active', 'options', ['question_id', 'is_active'], unique=False)
    op.create_index('idx_options_question_order', 'options', ['question_id', 'option_order'], unique=False)
    op.create_index(op.f('ix_options_dimension'), 'options', ['dimension'], unique=False)
    op.create_index(op.f('ix_options_is_active'), 'options', ['is_active'], unique=False)
    op.create_index(op.f('ix_options_option_order'), 'options', ['option_order'], unique=False)
    op.create_index(op.f('ix_options_question_id'), 'options', ['question_id'], unique=False)
    op.create_index('idx_questions_section_active', 'questions', ['section_id', 'is_active'], unique=False)
    op.create_index('idx_questions_test_active', 'questions', ['test_id', 'is_active'], unique=False)
    op.create_index('idx_questions_test_order', 'questions', ['test_id', 'question_order'], unique=False)
    op.create_index(op.f('ix_questions_is_active'), 'questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_questions_question_order'), 'questions', ['question_order'], unique=False)
    op.create_index(op.f('ix_questions_section_id'), 'questions', ['section_id'], unique=False)
    op.create_index(op.f('ix_questions_test_id'), 'questions', ['test_id'], unique=False)
    op.create_index('idx_config_test_active', 'test_result_configurations', ['test_id', 'is_active'], unique=False)
    op.create_index('idx_config_test_type', 'test_result_configurations', ['test_id', 'result_type'], unique=False)
    op.create_index('idx_config_type_code', 'test_result_configurations', ['result_type', 'result_code'], unique=False)
    op.create_index(op.f('ix_test_result_configurations_is_active'), 'test_result_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_test_result_configurations_result_code'), 'test_result_configurations', ['result_code'], unique=False)
    op.create_index(op.f('ix_test_result_configurations_result_type'), 'test_result_configurations', ['result_type'], unique=False)
    op.create_index('idx_result_details_result_type', 'test_result_details', ['test_result_id', 'dimension_type'], unique=False)
    op.create_index('idx_result_details_type_name', 'test_result_details', ['dimension_type', 'dimension_name'], unique=False)
    op.create_index(op.f('ix_test_result_details_dimension_name'), 'test_result_details', ['dimension_name'], unique=False)
    op.create_index(op.f('ix_test_result_details_dimension_type'), 'test_result_details', ['dimension_type'], unique=False)
    op.create_index(op.f('ix_test_result_details_level'), 'test_result_details', ['level'], unique=False)
    op.create_index(op.f('ix_test_result_details_percentage_score'), 'test_result_details', ['percentage_score'], unique=False)
    op.create_index(op.f('ix_test_result_details_test_result_id'), 'test_result_details', ['test_result_id'], unique=False)
    op.create_index('idx_test_results_completed_at', 'test_results', ['completed_at'], unique=False)
    op.create_index('idx_test_results_test_completed', 'test_results', ['test_id', 'is_completed'], unique=False)
    op.create_index('idx_test_results_user_completed', 'test_results', ['user_id', 'is_completed'], unique=False)
    op.create_index('idx_test_results_user_created', 'test_results', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_test_results_user_test', 'test_results', ['user_id', 'test_id'], unique=False)
    op.create_index(op.f('ix_test_results_completed_at'), 'test_results', ['completed_at'], unique=False)
    op.create_index(op.f('ix_test_results_created_at'), 'test_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_results_is_completed'), 'test_results', ['is_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_is_completed'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_created_at'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_completed_at'), table_name='test_results')
    op.drop_index('idx_test_results_user_test', table_name='test_results')
    op.drop_index('idx_test_results_user_created', table_name='test_results')
    op.drop_index('idx_test_results_user_completed', table_name='test_results')
    op.drop_index('idx_test_results_test_completed', table_name='test_results')
    op.drop_index('idx_test_results_completed_at', table_name='test_results')
    op.drop_index(op.f('ix_test_result_details_test_result_id'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_percentage_score'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_level'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_dimension_type'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_dimension_name'), table_name='test_result_details')
    op.drop_index('idx_result_details_type_name', table_name='test_result_details')
    op.drop_index('idx_result_details_result_type', table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_configurations_result_type'), table_name='test_result_configurations')
    op.drop_index(op.f('ix_test_result_configurations_result_code'), table_name='test_result_configurations')
    op.drop_index(op.f('ix_test_result_configurations_is_active'), table_name='test_result_configurations')
    op.drop_index('idx_config_type_code', table_name='test_result_configurations')
    op.drop_index('idx_config_test_type', table_name='test_result_configurations')
    op.drop_index('idx_config_test_active', table_name='test_result_configurations')
    op.drop_index(op.f('ix_questions_test_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_section_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_order'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_active'), table_name='questions')
    op.drop_index('idx_questions_test_order', table_name='questions')
    op.drop_index('idx_questions_test_active', table_name='questions')
    op.drop_index('idx_questions_section_active', table_name='questions')
    op.drop_index(op.f('ix_options_question_id'), table_name='options')
    op.drop_index(op.f('ix_options_option_order'), table_name='options')
    op.drop_index(op.f('ix_options_is_active'), table_name='options')
    op.drop_index(op.f('ix_options_dimension'), table_name='options')
    op.drop_index('idx_options_question_order', table_name='options')
    op.drop_index('idx_options_question_active', table_name='options')
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_status'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_model_used'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_insights_type'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_generation_duration'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_generated_at'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_created_at'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_confidence_score'), table_name='ai_insights')
    op.drop_index('idx_ai_insights_user_type', table_name='ai_insights')
    op.drop_index('idx_ai_insights_user_status', table_name='ai_insights')
    op.drop_index('idx_ai_insights_type_status', table_name='ai_insights')
    op.drop_index('idx_ai_insights_generated_at', table_name='ai_insights')
    # ### end Alembic commands ###