"""init

Revision ID: a01dd75f524d
Revises: 
Create Date: 2025-11-27 18:55:45.270126
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a01dd75f524d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('inquiry_type', sa.Enum('GENERAL', 'TECHNICAL', 'BILLING', 'PARTNERSHIP', 'FEEDBACK', name='inquirytype'), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='contactstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('english_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('questions_count', sa.Integer(), nullable=True),
    sa.Column('duration', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_active_created', 'tests', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_test_id_active', 'tests', ['test_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_index(op.f('ix_tests_is_active'), 'tests', ['is_active'], unique=False)
    op.create_index(op.f('ix_tests_test_id'), 'tests', ['test_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('providers', sa.JSON(), server_default='["password"]', nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=512), nullable=True),
    sa.Column('role', sa.VARCHAR(length=32), nullable=False),
    sa.Column('firebase_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('device', sa.VARCHAR(length=255), nullable=True),
    sa.Column('flag', sa.VARCHAR(length=255), nullable=True),
    sa.Column('payment_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','user')", name='ck_users_role_allowed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_active_created', 'users', ['is_active', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_index(op.f('ix_users_firebase_id'), 'users', ['firebase_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_payment_completed'), 'users', ['payment_completed'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index('ix_users_verified_created', 'users', ['is_verified', sa.text('created_at DESC')], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insights_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('insights_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.VARCHAR(length=50), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_results_used', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_insights_generated_at', 'ai_insights', [sa.text('generated_at DESC')], unique=False)
    op.create_index('idx_ai_insights_type_status', 'ai_insights', ['insights_type', 'status'], unique=False)
    op.create_index('idx_ai_insights_user_status_created', 'ai_insights', ['user_id', 'status', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_ai_insights_user_type_created', 'ai_insights', ['user_id', 'insights_type', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_ai_insights_confidence_score'), 'ai_insights', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_ai_insights_created_at'), 'ai_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_generated_at'), 'ai_insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_generation_duration'), 'ai_insights', ['generation_duration'], unique=False)
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    op.create_index(op.f('ix_ai_insights_insights_type'), 'ai_insights', ['insights_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_model_used'), 'ai_insights', ['model_used'], unique=False)
    op.create_index(op.f('ix_ai_insights_status'), 'ai_insights', ['status'], unique=False)
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    op.create_table('email_otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=8), nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("purpose IN ('verify_email','reset_password')", name='ck_emailotp_purpose'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otp_expires_at'), 'email_otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_otp_purpose'), 'email_otp', ['purpose'], unique=False)
    op.create_index(op.f('ix_email_otp_user_id'), 'email_otp', ['user_id'], unique=False)
    op.create_index('ix_emailotp_expires_at', 'email_otp', ['expires_at'], unique=False)
    op.create_index('ix_emailotp_user_purpose', 'email_otp', ['user_id', 'purpose'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('payment_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('signature', sa.VARCHAR(length=255), nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created','paid','failed')", name='ck_payments_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_payment_id', 'payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_created', 'payments', ['status', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_index('ix_payments_user_status_created', 'payments', ['user_id', 'status', sa.text('created_at DESC')], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_user_active', 'refresh_tokens', ['user_id'], unique=False, postgresql_where=sa.text('NOT is_revoked'))
    op.create_index('ix_refresh_user_created', 'refresh_tokens', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_table('test_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('english_name', sa.String(length=200), nullable=False),
    sa.Column('gujarati_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('careers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_dimensions_id'), 'test_dimensions', ['id'], unique=False)
    op.create_table('test_result_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('result_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('result_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('result_name_gujarati', sa.VARCHAR(length=200), nullable=False),
    sa.Column('result_name_english', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description_gujarati', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('description_english', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('scoring_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('careers', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('challenges', sa.JSON(), nullable=True),
    sa.Column('career_suggestions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_test_active', 'test_result_configurations', ['test_id', 'is_active'], unique=False)
    op.create_index('idx_config_test_type_active', 'test_result_configurations', ['test_id', 'result_type', 'is_active'], unique=False)
    op.create_index('idx_config_type_code', 'test_result_configurations', ['result_type', 'result_code'], unique=False)
    op.create_index(op.f('ix_test_result_configurations_id'), 'test_result_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_test_result_configurations_is_active'), 'test_result_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_test_result_configurations_result_code'), 'test_result_configurations', ['result_code'], unique=False)
    op.create_index(op.f('ix_test_result_configurations_result_type'), 'test_result_configurations', ['result_type'], unique=False)
    op.create_index(op.f('ix_test_result_configurations_test_id'), 'test_result_configurations', ['test_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('calculated_result', sa.JSON(), nullable=True),
    sa.Column('primary_result', sa.VARCHAR(length=100), nullable=True),
    sa.Column('result_summary', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_results_completed_at', 'test_results', [sa.text('completed_at DESC')], unique=False)
    op.create_index('idx_test_results_is_completed_created', 'test_results', ['is_completed', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_test_results_test_completed_created', 'test_results', ['test_id', 'is_completed', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_test_results_test_created', 'test_results', ['test_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_test_results_user_completed_created', 'test_results', ['user_id', 'is_completed', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_test_results_user_created', 'test_results', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_test_results_user_test_completed', 'test_results', ['user_id', 'test_id', 'is_completed'], unique=False)
    op.create_index(op.f('ix_test_results_completed_at'), 'test_results', ['completed_at'], unique=False)
    op.create_index(op.f('ix_test_results_created_at'), 'test_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_is_completed'), 'test_results', ['is_completed'], unique=False)
    op.create_index(op.f('ix_test_results_test_id'), 'test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_results_user_id'), 'test_results', ['user_id'], unique=False)
    op.create_table('test_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gujarati_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sections_id'), 'test_sections', ['id'], unique=False)
    op.create_table('calculated_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('calculated_result', sa.JSON(), nullable=False),
    sa.Column('primary_result', sa.VARCHAR(length=100), nullable=True),
    sa.Column('result_summary', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calc_result_test_result_id', 'calculated_test_results', ['test_result_id'], unique=False)
    op.create_index('idx_calc_result_user_created', 'calculated_test_results', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_calc_result_user_test_created', 'calculated_test_results', ['user_id', 'test_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_calc_result_valid_created', 'calculated_test_results', ['is_valid', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_calculated_test_results_created_at'), 'calculated_test_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_calculated_test_results_id'), 'calculated_test_results', ['id'], unique=False)
    op.create_index(op.f('ix_calculated_test_results_is_valid'), 'calculated_test_results', ['is_valid'], unique=False)
    op.create_index(op.f('ix_calculated_test_results_test_id'), 'calculated_test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_calculated_test_results_test_result_id'), 'calculated_test_results', ['test_result_id'], unique=False)
    op.create_index(op.f('ix_calculated_test_results_user_id'), 'calculated_test_results', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['test_sections.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_section_active_order', 'questions', ['section_id', 'is_active', 'question_order'], unique=False)
    op.create_index('idx_questions_test_active_order', 'questions', ['test_id', 'is_active', 'question_order'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_is_active'), 'questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_questions_question_order'), 'questions', ['question_order'], unique=False)
    op.create_index(op.f('ix_questions_section_id'), 'questions', ['section_id'], unique=False)
    op.create_index(op.f('ix_questions_test_id'), 'questions', ['test_id'], unique=False)
    op.create_table('test_result_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('dimension_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dimension_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('percentage_score', sa.Float(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_details_result_type_name', 'test_result_details', ['test_result_id', 'dimension_type', 'dimension_name'], unique=False)
    op.create_index('idx_result_details_type_score', 'test_result_details', ['dimension_type', sa.text('percentage_score DESC')], unique=False)
    op.create_index(op.f('ix_test_result_details_dimension_name'), 'test_result_details', ['dimension_name'], unique=False)
    op.create_index(op.f('ix_test_result_details_dimension_type'), 'test_result_details', ['dimension_type'], unique=False)
    op.create_index(op.f('ix_test_result_details_id'), 'test_result_details', ['id'], unique=False)
    op.create_index(op.f('ix_test_result_details_level'), 'test_result_details', ['level'], unique=False)
    op.create_index(op.f('ix_test_result_details_percentage_score'), 'test_result_details', ['percentage_score'], unique=False)
    op.create_index(op.f('ix_test_result_details_test_result_id'), 'test_result_details', ['test_result_id'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=10), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('option_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_options_dimension_active', 'options', ['dimension', 'is_active'], unique=False)
    op.create_index('idx_options_question_active_order', 'options', ['question_id', 'is_active', 'option_order'], unique=False)
    op.create_index(op.f('ix_options_dimension'), 'options', ['dimension'], unique=False)
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    op.create_index(op.f('ix_options_is_active'), 'options', ['is_active'], unique=False)
    op.create_index(op.f('ix_options_option_order'), 'options', ['option_order'], unique=False)
    op.create_index(op.f('ix_options_question_id'), 'options', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_question_id'), table_name='options')
    op.drop_index(op.f('ix_options_option_order'), table_name='options')
    op.drop_index(op.f('ix_options_is_active'), table_name='options')
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_index(op.f('ix_options_dimension'), table_name='options')
    op.drop_index('idx_options_question_active_order', table_name='options')
    op.drop_index('idx_options_dimension_active', table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_test_result_details_test_result_id'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_percentage_score'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_level'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_id'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_dimension_type'), table_name='test_result_details')
    op.drop_index(op.f('ix_test_result_details_dimension_name'), table_name='test_result_details')
    op.drop_index('idx_result_details_type_score', table_name='test_result_details')
    op.drop_index('idx_result_details_result_type_name', table_name='test_result_details')
    op.drop_table('test_result_details')
    op.drop_index(op.f('ix_questions_test_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_section_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_order'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_active'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index('idx_questions_test_active_order', table_name='questions')
    op.drop_index('idx_questions_section_active_order', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_calculated_test_results_user_id'), table_name='calculated_test_results')
    op.drop_index(op.f('ix_calculated_test_results_test_result_id'), table_name='calculated_test_results')
    op.drop_index(op.f('ix_calculated_test_results_test_id'), table_name='calculated_test_results')
    op.drop_index(op.f('ix_calculated_test_results_is_valid'), table_name='calculated_test_results')
    op.drop_index(op.f('ix_calculated_test_results_id'), table_name='calculated_test_results')
    op.drop_index(op.f('ix_calculated_test_results_created_at'), table_name='calculated_test_results')
    op.drop_index('idx_calc_result_valid_created', table_name='calculated_test_results')
    op.drop_index('idx_calc_result_user_test_created', table_name='calculated_test_results')
    op.drop_index('idx_calc_result_user_created', table_name='calculated_test_results')
    op.drop_index('idx_calc_result_test_result_id', table_name='calculated_test_results')
    op.drop_table('calculated_test_results')
    op.drop_index(op.f('ix_test_sections_id'), table_name='test_sections')
    op.drop_table('test_sections')
    op.drop_index(op.f('ix_test_results_user_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_is_completed'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_created_at'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_completed_at'), table_name='test_results')
    op.drop_index('idx_test_results_user_test_completed', table_name='test_results')
    op.drop_index('idx_test_results_user_created', table_name='test_results')
    op.drop_index('idx_test_results_user_completed_created', table_name='test_results')
    op.drop_index('idx_test_results_test_created', table_name='test_results')
    op.drop_index('idx_test_results_test_completed_created', table_name='test_results')
    op.drop_index('idx_test_results_is_completed_created', table_name='test_results')
    op.drop_index('idx_test_results_completed_at', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_result_configurations_test_id'), table_name='test_result_configurations')
    op.drop_index(op.f('ix_test_result_configurations_result_type'), table_name='test_result_configurations')
    op.drop_index(op.f('ix_test_result_configurations_result_code'), table_name='test_result_configurations')
    op.drop_index(op.f('ix_test_result_configurations_is_active'), table_name='test_result_configurations')
    op.drop_index(op.f('ix_test_result_configurations_id'), table_name='test_result_configurations')
    op.drop_index('idx_config_type_code', table_name='test_result_configurations')
    op.drop_index('idx_config_test_type_active', table_name='test_result_configurations')
    op.drop_index('idx_config_test_active', table_name='test_result_configurations')
    op.drop_table('test_result_configurations')
    op.drop_index(op.f('ix_test_dimensions_id'), table_name='test_dimensions')
    op.drop_table('test_dimensions')
    op.drop_index('ix_refresh_user_created', table_name='refresh_tokens')
    op.drop_index('ix_refresh_user_active', table_name='refresh_tokens', postgresql_where=sa.text('NOT is_revoked'))
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_payments_user_status_created', table_name='payments')
    op.drop_index('ix_payments_user_id', table_name='payments')
    op.drop_index('ix_payments_status_created', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index('ix_payments_payment_id', table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_emailotp_user_purpose', table_name='email_otp')
    op.drop_index('ix_emailotp_expires_at', table_name='email_otp')
    op.drop_index(op.f('ix_email_otp_user_id'), table_name='email_otp')
    op.drop_index(op.f('ix_email_otp_purpose'), table_name='email_otp')
    op.drop_index(op.f('ix_email_otp_expires_at'), table_name='email_otp')
    op.drop_table('email_otp')
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_status'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_model_used'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_insights_type'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_generation_duration'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_generated_at'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_created_at'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_confidence_score'), table_name='ai_insights')
    op.drop_index('idx_ai_insights_user_type_created', table_name='ai_insights')
    op.drop_index('idx_ai_insights_user_status_created', table_name='ai_insights')
    op.drop_index('idx_ai_insights_type_status', table_name='ai_insights')
    op.drop_index('idx_ai_insights_generated_at', table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index('ix_users_verified_created', table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_payment_completed'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_id'), table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index('ix_users_active_created', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tests_test_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_is_active'), table_name='tests')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_index('idx_test_id_active', table_name='tests')
    op.drop_index('idx_test_active_created', table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###