"""Add question_type column to questions table

Revision ID: b0b756c6737a
Revises: 28732ba14a0a
Create Date: 2025-09-14 10:17:47.112023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b0b756c6737a'
down_revision: Union[str, None] = '28732ba14a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###