"""add col for mbit

Revision ID: c026610932f3
Revises: f8758c76922e
Create Date: 2025-11-03 11:15:40.259609
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c026610932f3'
down_revision: Union[str, None] = 'f8758c76922e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result_configurations', sa.Column('characteristics', sa.JSON(), nullable=True))
    op.add_column('test_result_configurations', sa.Column('challenges', sa.JSON(), nullable=True))
    op.add_column('test_result_configurations', sa.Column('career_suggestions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_result_configurations', 'career_suggestions')
    op.drop_column('test_result_configurations', 'challenges')
    op.drop_column('test_result_configurations', 'characteristics')
    # ### end Alembic commands ###