"""add index

Revision ID: f94f8f452d40
Revises: 5e3a43662f85
Create Date: 2025-11-27 16:29:27.342030
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94f8f452d40'
down_revision: Union[str, None] = '5e3a43662f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ai_insights_user_created', 'ai_insights', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_ai_insights_user_generated', 'ai_insights', ['user_id', 'generated_at'], unique=False)
    op.create_index('idx_test_results_is_completed_created', 'test_results', ['is_completed', 'created_at'], unique=False)
    op.create_index('idx_test_results_test_type_created', 'test_results', ['test_id', 'created_at'], unique=False)
    op.create_index('idx_test_results_user_test_completed', 'test_results', ['user_id', 'test_id', 'is_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_test_results_user_test_completed', table_name='test_results')
    op.drop_index('idx_test_results_test_type_created', table_name='test_results')
    op.drop_index('idx_test_results_is_completed_created', table_name='test_results')
    op.drop_index('idx_ai_insights_user_generated', table_name='ai_insights')
    op.drop_index('idx_ai_insights_user_created', table_name='ai_insights')
    # ### end Alembic commands ###